name: Ejecucion de Tests Automatizados

on: [push]

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargando el codigo del repo
        uses: actions/checkout@v4

      - name: 2. Instalando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar Google Chrome (El navegador)
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      
      - name: 4. Instalar ChromeDriver (El puente)
        uses: nanasess/setup-chromedriver@master

      - name: 5. Instalando Librerias
        run: |
          pip install selenium pytest webdriver-manager

      - name: 6. Corriendo mis tests de QA
        run: |
          pytest
